# Generated by Django 6.1.1 on 2026-09-14 03:11

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PaymentTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("user_id", models.CharField(db_index=True, max_length=50)),
                (
                    "type",
                    models.CharField(
                        choices=[("expense", "Expense"), ("income", "Income")],
                        max_length=10,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("currency", models.CharField(default="THB", max_length=3)),
                ("category", models.CharField(max_length=50)),
                ("note", models.TextField(blank=True, null=True)),
                ("occurred_at", models.DateField(db_index=True)),
                ("confidence", models.FloatField()),
                ("source_text", models.TextField()),
                ("create_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user_id", "occurred_at"],
                        name="portal_paym_user_id_feb13e_idx",
                    ),
                    models.Index(
                        fields=["user_id", "category", "occurred_at"],
                        name="portal_paym_user_id_adee42_idx",
                    ),
                ],
            },
        ),
    ]
