# Generated by Django 6.1.1 on 2026-09-14 03:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("portal", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="paymenttransaction",
            new_name="payment_tra_user_id_874b7b_idx",
            old_name="portal_paym_user_id_feb13e_idx",
        ),
        migrations.RenameIndex(
            model_name="paymenttransaction",
            new_name="payment_tra_user_id_22156c_idx",
            old_name="portal_paym_user_id_adee42_idx",
        ),
        migrations.AlterModelTable(
            name="paymenttransaction",
            table="payment_transaction",
        ),
    ]
