# Generated by Django 6.1.1 on 2026-09-14 04:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "portal",
            "0002_rename_portal_paym_user_id_feb13e_idx_payment_tra_user_id_874b7b_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymenttransaction",
            name="create_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
