# Generated by Django 6.1.1 on 2026-09-14 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_alter_paymenttransaction_create_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymenttransaction',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
