# Generated by Django 6.1.1 on 2026-09-17 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_rename_create_at_paymenttransaction_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTransactionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_key', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='portal.paymenttransaction')),
            ],
            options={
                'db_table': 'payment_transaction_image',
            },
        ),
    ]
