services:
  db:
    image: postgres:17
    container_name: db
    environment:
      POSTGRES_DB: portal_penny_db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data:
